#############################################################################
# Makefile for building: flarecore
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon Sep 26 11:05:53 2011
# Project:  flarecore.pro
# Template: app
# Command: /opt/QtSDK/Desktop/Qt/474/gcc/bin/qmake -o Makefile flarecore.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/default -I. -I/opt/QtSDK/Desktop/Qt/474/gcc/include/QtUiTools -I/opt/QtSDK/Desktop/Qt/474/gcc/include/QtCore -I/opt/QtSDK/Desktop/Qt/474/gcc/include/QtGui -I/opt/QtSDK/Desktop/Qt/474/gcc/include/QtXml -I/opt/QtSDK/Desktop/Qt/474/gcc/include/QtWebKit -I/opt/QtSDK/Desktop/Qt/474/gcc/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/QtSDK/Desktop/Qt/474/gcc/lib
LIBS          = $(SUBLIBS)  -L/opt/QtSDK/Desktop/Qt/474/gcc/lib -lQtWebKit -lQtXml -lQtGui -lQtCore -lQtUiTools -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = codeeditor.cpp \
		cssdocument.cpp \
		document.cpp \
		finddialog.cpp \
		flare.cpp \
		flexdocument.cpp \
		foundry.cpp \
		htmldocument.cpp \
		jsdocument.cpp \
		main.cpp \
		manageprojectsdialog.cpp \
		newfiledialog.cpp \
		phpdocument.cpp \
		project.cpp \
		projectdialog.cpp \
		settings.cpp \
		switchproject.cpp \
		syntaxhighlighter.cpp \
		textdocument.cpp \
		qtc-gdbmacros/gdbmacros.cpp \
		completer.cpp \
		insertselectmenudialog.cpp \
		insertbuttongroup.cpp \
		insertregistrationform.cpp moc_cssdocument.cpp \
		moc_document.cpp \
		moc_finddialog.cpp \
		moc_flare.cpp \
		moc_flexdocument.cpp \
		moc_foundry.cpp \
		moc_htmldocument.cpp \
		moc_jsdocument.cpp \
		moc_manageprojectsdialog.cpp \
		moc_newfiledialog.cpp \
		moc_phpdocument.cpp \
		moc_projectdialog.cpp \
		moc_switchproject.cpp \
		moc_syntaxhighlighter.cpp \
		moc_codeeditor.cpp \
		moc_insertselectmenudialog.cpp \
		moc_insertbuttongroup.cpp \
		moc_insertregistrationform.cpp \
		qrc_resources.cpp
OBJECTS       = codeeditor.o \
		cssdocument.o \
		document.o \
		finddialog.o \
		flare.o \
		flexdocument.o \
		foundry.o \
		htmldocument.o \
		jsdocument.o \
		main.o \
		manageprojectsdialog.o \
		newfiledialog.o \
		phpdocument.o \
		project.o \
		projectdialog.o \
		settings.o \
		switchproject.o \
		syntaxhighlighter.o \
		textdocument.o \
		gdbmacros.o \
		completer.o \
		insertselectmenudialog.o \
		insertbuttongroup.o \
		insertregistrationform.o \
		moc_cssdocument.o \
		moc_document.o \
		moc_finddialog.o \
		moc_flare.o \
		moc_flexdocument.o \
		moc_foundry.o \
		moc_htmldocument.o \
		moc_jsdocument.o \
		moc_manageprojectsdialog.o \
		moc_newfiledialog.o \
		moc_phpdocument.o \
		moc_projectdialog.o \
		moc_switchproject.o \
		moc_syntaxhighlighter.o \
		moc_codeeditor.o \
		moc_insertselectmenudialog.o \
		moc_insertbuttongroup.o \
		moc_insertregistrationform.o \
		qrc_resources.o
DIST          = /opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/static.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uitools.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		flarecore.pro
QMAKE_TARGET  = flarecore
DESTDIR       = 
TARGET        = flarecore

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_FindDiag.h ui_flare.h ui_manageprojectsdialog.h ui_newfiledialog.h ui_projectdialog.h ui_switchproject.h ui_inserttextfield.h ui_inserttextarea.h ui_insertradiobutton.h ui_insertbutton.h ui_insertselectmenu.h ui_ftpclient.h ui_addselectmenuitem.h ui_insertbuttongroup.h ui_insertlink.h ui_aboutdialog.h ui_insertregistrationform.h ui_inserttable.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: flarecore.pro  /opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/default/qmake.conf /opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/static.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uitools.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile flarecore.pro
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/static.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uitools.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
/opt/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile flarecore.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/flarecore1.0.0 || $(MKDIR) .tmp/flarecore1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/flarecore1.0.0/ && $(COPY_FILE) --parents cssdocument.h document.h finddialog.h flare.h flexdocument.h foundry.h globals.h htmldocument.h jsdocument.h manageprojectsdialog.h newfiledialog.h phpdocument.h project.h projectdialog.h settings.h switchproject.h syntaxhighlighter.h textdocument.h codeeditor.h completer.h insertselectmenudialog.h insertbuttongroup.h insertregistrationform.h .tmp/flarecore1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/flarecore1.0.0/ && $(COPY_FILE) --parents codeeditor.cpp cssdocument.cpp document.cpp finddialog.cpp flare.cpp flexdocument.cpp foundry.cpp htmldocument.cpp jsdocument.cpp main.cpp manageprojectsdialog.cpp newfiledialog.cpp phpdocument.cpp project.cpp projectdialog.cpp settings.cpp switchproject.cpp syntaxhighlighter.cpp textdocument.cpp qtc-gdbmacros/gdbmacros.cpp completer.cpp insertselectmenudialog.cpp insertbuttongroup.cpp insertregistrationform.cpp .tmp/flarecore1.0.0/ && $(COPY_FILE) --parents FindDiag.ui flare.ui manageprojectsdialog.ui newfiledialog.ui projectdialog.ui switchproject.ui resources/htmldialogs/inserttextfield.ui resources/htmldialogs/inserttextarea.ui resources/htmldialogs/insertradiobutton.ui resources/htmldialogs/insertbutton.ui resources/htmldialogs/insertselectmenu.ui ftpclient.ui resources/htmldialogs/addselectmenuitem.ui insertbuttongroup.ui resources/htmldialogs/insertlink.ui resources/aboutdialog.ui resources/htmldialogs/insertregistrationform.ui resources/htmldialogs/inserttable.ui .tmp/flarecore1.0.0/ && (cd `dirname .tmp/flarecore1.0.0` && $(TAR) flarecore1.0.0.tar flarecore1.0.0 && $(COMPRESS) flarecore1.0.0.tar) && $(MOVE) `dirname .tmp/flarecore1.0.0`/flarecore1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/flarecore1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cssdocument.cpp moc_document.cpp moc_finddialog.cpp moc_flare.cpp moc_flexdocument.cpp moc_foundry.cpp moc_htmldocument.cpp moc_jsdocument.cpp moc_manageprojectsdialog.cpp moc_newfiledialog.cpp moc_phpdocument.cpp moc_projectdialog.cpp moc_switchproject.cpp moc_syntaxhighlighter.cpp moc_codeeditor.cpp moc_insertselectmenudialog.cpp moc_insertbuttongroup.cpp moc_insertregistrationform.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cssdocument.cpp moc_document.cpp moc_finddialog.cpp moc_flare.cpp moc_flexdocument.cpp moc_foundry.cpp moc_htmldocument.cpp moc_jsdocument.cpp moc_manageprojectsdialog.cpp moc_newfiledialog.cpp moc_phpdocument.cpp moc_projectdialog.cpp moc_switchproject.cpp moc_syntaxhighlighter.cpp moc_codeeditor.cpp moc_insertselectmenudialog.cpp moc_insertbuttongroup.cpp moc_insertregistrationform.cpp
moc_cssdocument.cpp: document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		foundry.h \
		cssdocument.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) cssdocument.h -o moc_cssdocument.cpp

moc_document.cpp: codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		document.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) document.h -o moc_document.cpp

moc_finddialog.cpp: ui_FindDiag.h \
		finddialog.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) finddialog.h -o moc_finddialog.cpp

moc_flare.cpp: foundry.h \
		globals.h \
		newfiledialog.h \
		ui_newfiledialog.h \
		finddialog.h \
		ui_FindDiag.h \
		htmldocument.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		jsdocument.h \
		phpdocument.h \
		project.h \
		flare.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) flare.h -o moc_flare.cpp

moc_flexdocument.cpp: syntaxhighlighter.h \
		codeeditor.h \
		completer.h \
		document.h \
		finddialog.h \
		ui_FindDiag.h \
		flexdocument.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) flexdocument.h -o moc_flexdocument.cpp

moc_foundry.cpp: foundry.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) foundry.h -o moc_foundry.cpp

moc_htmldocument.cpp: document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		htmldocument.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) htmldocument.h -o moc_htmldocument.cpp

moc_jsdocument.cpp: document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		jsdocument.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) jsdocument.h -o moc_jsdocument.cpp

moc_manageprojectsdialog.cpp: ui_manageprojectsdialog.h \
		project.h \
		projectdialog.h \
		ui_projectdialog.h \
		manageprojectsdialog.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) manageprojectsdialog.h -o moc_manageprojectsdialog.cpp

moc_newfiledialog.cpp: ui_newfiledialog.h \
		newfiledialog.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) newfiledialog.h -o moc_newfiledialog.cpp

moc_phpdocument.cpp: document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		phpdocument.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) phpdocument.h -o moc_phpdocument.cpp

moc_projectdialog.cpp: ui_projectdialog.h \
		projectdialog.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) projectdialog.h -o moc_projectdialog.cpp

moc_switchproject.cpp: ui_switchproject.h \
		switchproject.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) switchproject.h -o moc_switchproject.cpp

moc_syntaxhighlighter.cpp: syntaxhighlighter.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) syntaxhighlighter.h -o moc_syntaxhighlighter.cpp

moc_codeeditor.cpp: completer.h \
		codeeditor.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) codeeditor.h -o moc_codeeditor.cpp

moc_insertselectmenudialog.cpp: ui_insertselectmenu.h \
		insertselectmenudialog.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) insertselectmenudialog.h -o moc_insertselectmenudialog.cpp

moc_insertbuttongroup.cpp: ui_insertbuttongroup.h \
		insertbuttongroup.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) insertbuttongroup.h -o moc_insertbuttongroup.cpp

moc_insertregistrationform.cpp: ui_insertregistrationform.h \
		insertregistrationform.h
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) insertregistrationform.h -o moc_insertregistrationform.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		icons/flash.png \
		icons/text_superscript.png \
		icons/textfield.png \
		icons/text_list_bullets.png \
		icons/calendar.png \
		icons/download.png \
		resources/htmldialogs/inserttable.ui \
		icons/resultset_previous.png \
		icons/jquery.jpg \
		icons/Upload.png \
		icons/document-open.png \
		icons/preferences-system-login.png \
		icons/table_multiple.png \
		resources/htmltaglist.txt \
		icons/copy.png \
		icons/document-open-recent.png \
		icons/codeview.png \
		icons/text_underline.png \
		icons/help.png \
		resources/htmldialogs/insertlink.ui \
		icons/color_wheel.png \
		icons/page_white_find.png \
		icons/text_list_numbers.png \
		resources/htmldialogs/inserttextfield.ui \
		icons/gtk-close.png \
		icons/css.png \
		icons/php.png \
		icons/package_settings.png \
		icons/new.png \
		icons/text_heading_3.png \
		icons/text_heading_6.png \
		icons/color_swatch.png \
		icons/cut.png \
		icons/insert_table_col.png \
		icons/script.png \
		resources/htmldialogs/insertradiobutton.ui \
		icons/arrow_redo.png \
		icons/script_add.png \
		resources/htmldialogs/insertbutton.ui \
		resources/phpfunctions.txt \
		icons/application_side_tree.png \
		icons/application_form.png \
		icons/html.png \
		icons/anchor.png \
		icons/javascript.png \
		icons/edit-select-all.png \
		icons/hidecamerafolders_128x128.png \
		icons/text_subscript.png \
		icons/clean.png \
		icons/printer.png \
		icons/text_align_justify.png \
		icons/text_align_left.png \
		icons/emblem-calendar.png \
		icons/text_heading_4.png \
		icons/emblem-special.png \
		icons/text_align_center.png \
		icons/table_save.png \
		icons/document-properties.png \
		icons/delete_table_col.png \
		icons/mergecell.png \
		icons/stock_save-as.png \
		resources/flextaglist.txt \
		icons/text_indent.png \
		icons/gtk-dialog-question.png \
		icons/text_italic.png \
		icons/lightning.png \
		icons/text_bold.png \
		icons/comments.png \
		icons/move.png \
		icons/project_create.png \
		icons/save.png \
		icons/resultset_next.png \
		icons/draw-brush.png \
		icons/tab-new.png \
		icons/text_align_right.png \
		resources/library/jquery-1.3.2.min.js \
		icons/stock_exit.png \
		icons/about.png \
		icons/script_icon.png \
		icons/text_indent_remove.png \
		icons/application_side_list.png \
		icons/text_heading_5.png \
		icons/world_link.png \
		icons/stylesheet.png \
		icons/paste.png \
		icons/source_java.png \
		icons/application_side_boxes.png \
		icons/image-jpeg2000.png \
		icons/template_source.png \
		icons/insert_table_row.png \
		icons/delete_table_row.png \
		icons/text_heading_1.png \
		icons/window_new.png \
		icons/application_split.png \
		icons/arrow_undo.png \
		resources/htmldialogs/addselectmenuitem.ui \
		icons/application_cascade.png \
		icons/page_white_code.png \
		icons/resize.png \
		icons/text_horizontalrule.png \
		resources/htmldialogs/inserttextarea.ui \
		resources/cssrules.txt \
		icons/text_heading_2.png \
		icons/password_field.png \
		icons/application_edit.png \
		icons/table.png \
		resources/aboutdialog.ui \
		icons/document-save-all.png \
		resources/templates/countrylist.txt \
		icons/go-down.png \
		icons/delete.png \
		icons/go-up.png \
		icons/arrow-right.png
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_FindDiag.h ui_flare.h ui_manageprojectsdialog.h ui_newfiledialog.h ui_projectdialog.h ui_switchproject.h ui_inserttextfield.h ui_inserttextarea.h ui_insertradiobutton.h ui_insertbutton.h ui_insertselectmenu.h ui_ftpclient.h ui_addselectmenuitem.h ui_insertbuttongroup.h ui_insertlink.h ui_aboutdialog.h ui_insertregistrationform.h ui_inserttable.h
compiler_uic_clean:
	-$(DEL_FILE) ui_FindDiag.h ui_flare.h ui_manageprojectsdialog.h ui_newfiledialog.h ui_projectdialog.h ui_switchproject.h ui_inserttextfield.h ui_inserttextarea.h ui_insertradiobutton.h ui_insertbutton.h ui_insertselectmenu.h ui_ftpclient.h ui_addselectmenuitem.h ui_insertbuttongroup.h ui_insertlink.h ui_aboutdialog.h ui_insertregistrationform.h ui_inserttable.h
ui_FindDiag.h: FindDiag.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic FindDiag.ui -o ui_FindDiag.h

ui_flare.h: flare.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic flare.ui -o ui_flare.h

ui_manageprojectsdialog.h: manageprojectsdialog.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic manageprojectsdialog.ui -o ui_manageprojectsdialog.h

ui_newfiledialog.h: newfiledialog.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic newfiledialog.ui -o ui_newfiledialog.h

ui_projectdialog.h: projectdialog.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic projectdialog.ui -o ui_projectdialog.h

ui_switchproject.h: switchproject.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic switchproject.ui -o ui_switchproject.h

ui_inserttextfield.h: resources/htmldialogs/inserttextfield.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/inserttextfield.ui -o ui_inserttextfield.h

ui_inserttextarea.h: resources/htmldialogs/inserttextarea.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/inserttextarea.ui -o ui_inserttextarea.h

ui_insertradiobutton.h: resources/htmldialogs/insertradiobutton.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/insertradiobutton.ui -o ui_insertradiobutton.h

ui_insertbutton.h: resources/htmldialogs/insertbutton.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/insertbutton.ui -o ui_insertbutton.h

ui_insertselectmenu.h: resources/htmldialogs/insertselectmenu.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/insertselectmenu.ui -o ui_insertselectmenu.h

ui_ftpclient.h: ftpclient.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic ftpclient.ui -o ui_ftpclient.h

ui_addselectmenuitem.h: resources/htmldialogs/addselectmenuitem.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/addselectmenuitem.ui -o ui_addselectmenuitem.h

ui_insertbuttongroup.h: insertbuttongroup.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic insertbuttongroup.ui -o ui_insertbuttongroup.h

ui_insertlink.h: resources/htmldialogs/insertlink.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/insertlink.ui -o ui_insertlink.h

ui_aboutdialog.h: resources/aboutdialog.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/aboutdialog.ui -o ui_aboutdialog.h

ui_insertregistrationform.h: resources/htmldialogs/insertregistrationform.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/insertregistrationform.ui -o ui_insertregistrationform.h

ui_inserttable.h: resources/htmldialogs/inserttable.ui
	/opt/QtSDK/Desktop/Qt/474/gcc/bin/uic resources/htmldialogs/inserttable.ui -o ui_inserttable.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

codeeditor.o: codeeditor.cpp codeeditor.h \
		completer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeeditor.o codeeditor.cpp

cssdocument.o: cssdocument.cpp cssdocument.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		foundry.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cssdocument.o cssdocument.cpp

document.o: document.cpp document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o document.cpp

finddialog.o: finddialog.cpp finddialog.h \
		ui_FindDiag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o finddialog.o finddialog.cpp

flare.o: flare.cpp flare.h \
		foundry.h \
		globals.h \
		newfiledialog.h \
		ui_newfiledialog.h \
		finddialog.h \
		ui_FindDiag.h \
		htmldocument.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		jsdocument.h \
		phpdocument.h \
		project.h \
		ui_flare.h \
		settings.h \
		projectdialog.h \
		ui_projectdialog.h \
		manageprojectsdialog.h \
		ui_manageprojectsdialog.h \
		switchproject.h \
		ui_switchproject.h \
		flexdocument.h \
		cssdocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flare.o flare.cpp

flexdocument.o: flexdocument.cpp flexdocument.h \
		syntaxhighlighter.h \
		codeeditor.h \
		completer.h \
		document.h \
		finddialog.h \
		ui_FindDiag.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flexdocument.o flexdocument.cpp

foundry.o: foundry.cpp foundry.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o foundry.o foundry.cpp

htmldocument.o: htmldocument.cpp htmldocument.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		insertselectmenudialog.h \
		ui_insertselectmenu.h \
		insertbuttongroup.h \
		ui_insertbuttongroup.h \
		insertregistrationform.h \
		ui_insertregistrationform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o htmldocument.o htmldocument.cpp

jsdocument.o: jsdocument.cpp jsdocument.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jsdocument.o jsdocument.cpp

main.o: main.cpp flare.h \
		foundry.h \
		globals.h \
		newfiledialog.h \
		ui_newfiledialog.h \
		finddialog.h \
		ui_FindDiag.h \
		htmldocument.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		jsdocument.h \
		phpdocument.h \
		project.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

manageprojectsdialog.o: manageprojectsdialog.cpp manageprojectsdialog.h \
		ui_manageprojectsdialog.h \
		project.h \
		projectdialog.h \
		ui_projectdialog.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manageprojectsdialog.o manageprojectsdialog.cpp

newfiledialog.o: newfiledialog.cpp newfiledialog.h \
		ui_newfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newfiledialog.o newfiledialog.cpp

phpdocument.o: phpdocument.cpp phpdocument.h \
		document.h \
		codeeditor.h \
		completer.h \
		syntaxhighlighter.h \
		finddialog.h \
		ui_FindDiag.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phpdocument.o phpdocument.cpp

project.o: project.cpp project.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project.o project.cpp

projectdialog.o: projectdialog.cpp projectdialog.h \
		ui_projectdialog.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectdialog.o projectdialog.cpp

settings.o: settings.cpp settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

switchproject.o: switchproject.cpp switchproject.h \
		ui_switchproject.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o switchproject.o switchproject.cpp

syntaxhighlighter.o: syntaxhighlighter.cpp syntaxhighlighter.h \
		settings.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syntaxhighlighter.o syntaxhighlighter.cpp

textdocument.o: textdocument.cpp textdocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textdocument.o textdocument.cpp

gdbmacros.o: qtc-gdbmacros/gdbmacros.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gdbmacros.o qtc-gdbmacros/gdbmacros.cpp

completer.o: completer.cpp completer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o completer.o completer.cpp

insertselectmenudialog.o: insertselectmenudialog.cpp insertselectmenudialog.h \
		ui_insertselectmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o insertselectmenudialog.o insertselectmenudialog.cpp

insertbuttongroup.o: insertbuttongroup.cpp insertbuttongroup.h \
		ui_insertbuttongroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o insertbuttongroup.o insertbuttongroup.cpp

insertregistrationform.o: insertregistrationform.cpp insertregistrationform.h \
		ui_insertregistrationform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o insertregistrationform.o insertregistrationform.cpp

moc_cssdocument.o: moc_cssdocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cssdocument.o moc_cssdocument.cpp

moc_document.o: moc_document.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_document.o moc_document.cpp

moc_finddialog.o: moc_finddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_finddialog.o moc_finddialog.cpp

moc_flare.o: moc_flare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_flare.o moc_flare.cpp

moc_flexdocument.o: moc_flexdocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_flexdocument.o moc_flexdocument.cpp

moc_foundry.o: moc_foundry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_foundry.o moc_foundry.cpp

moc_htmldocument.o: moc_htmldocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_htmldocument.o moc_htmldocument.cpp

moc_jsdocument.o: moc_jsdocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jsdocument.o moc_jsdocument.cpp

moc_manageprojectsdialog.o: moc_manageprojectsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_manageprojectsdialog.o moc_manageprojectsdialog.cpp

moc_newfiledialog.o: moc_newfiledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newfiledialog.o moc_newfiledialog.cpp

moc_phpdocument.o: moc_phpdocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_phpdocument.o moc_phpdocument.cpp

moc_projectdialog.o: moc_projectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectdialog.o moc_projectdialog.cpp

moc_switchproject.o: moc_switchproject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_switchproject.o moc_switchproject.cpp

moc_syntaxhighlighter.o: moc_syntaxhighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_syntaxhighlighter.o moc_syntaxhighlighter.cpp

moc_codeeditor.o: moc_codeeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codeeditor.o moc_codeeditor.cpp

moc_insertselectmenudialog.o: moc_insertselectmenudialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_insertselectmenudialog.o moc_insertselectmenudialog.cpp

moc_insertbuttongroup.o: moc_insertbuttongroup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_insertbuttongroup.o moc_insertbuttongroup.cpp

moc_insertregistrationform.o: moc_insertregistrationform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_insertregistrationform.o moc_insertregistrationform.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

